DROP TABLE IF EXISTS PATS;
DROP TABLE IF EXISTS PATSNAPS;
DROP TABLE IF EXISTS PET_PALS;
DROP TABLE IF EXISTS PET_TYPES;
DROP TABLE IF EXISTS TYPES;
DROP TABLE IF EXISTS PETS;
DROP TABLE IF EXISTS USERS_LOG;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS HOUSE;
CREATE TABLE IF NOT EXISTS HOUSE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    banner TEXT,
    createdAt DATETIME,
    modifiedAt DATETIME,
    deletedAt DATETIME
);
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idHouse INT,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(50),
    isVerified BOOLEAN DEFAULT FALSE,
    isBanned BOOLEAN DEFAULT FALSE,
    avatar TEXT,
    createdAt DATETIME,
    modifiedAt DATETIME,
    deletedAt DATETIME,
    FOREIGN KEY (idHouse) REFERENCES HOUSE(id)
);
CREATE TABLE IF NOT EXISTS USERS_LOG (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idUser INT,
    date DATETIME,
    token VARCHAR(255),
    expiration DATETIME,
    state ENUM('ok', 'error', 'locked', 'email'),
    FOREIGN KEY (idUser) REFERENCES USERS(id)
);
DROP TABLE IF EXISTS PET_CATEGORIES;
CREATE TABLE IF NOT EXISTS PET_CATEGORIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);
DROP TABLE IF EXISTS PET_COLORS;
CREATE TABLE IF NOT EXISTS PET_COLORS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS PETS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idHouse INT,
    name VARCHAR(255),
    avatar TEXT,
    idCategory INT,
    idColor INT,
    FOREIGN KEY (idHouse) REFERENCES HOUSE(id),
    FOREIGN KEY (idCategory) REFERENCES PET_CATEGORIES(id),
    FOREIGN KEY (idColor) REFERENCES PET_COLORS(id)
);
CREATE TABLE IF NOT EXISTS TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    idParent INT,
    FOREIGN KEY (idParent) REFERENCES TYPES(id)
);
CREATE TABLE IF NOT EXISTS PET_TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    idType INT,
    FOREIGN KEY (idPet) REFERENCES PETS(id),
    FOREIGN KEY (idType) REFERENCES TYPES(id)
);
CREATE TABLE IF NOT EXISTS PET_PALS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    idPal INT,
    becamePalsAt DATETIME,
    FOREIGN KEY (idPet) REFERENCES PETS(id),
    FOREIGN KEY (idPal) REFERENCES PETS(id)
);
CREATE TABLE IF NOT EXISTS PATSNAPS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    date DATETIME,
    caption TEXT,
    image TEXT,
    FOREIGN KEY (idPet) REFERENCES PETS(id)
);
CREATE TABLE IF NOT EXISTS PATS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPost INT,
    date DATETIME,
    FOREIGN KEY (idPost) REFERENCES PATSNAPS(id)
);