DROP TABLE IF EXISTS HOUSE;
CREATE TABLE IF NOT EXISTS HOUSE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    banner TEXT,
    createdAt DATETIME,
    modifiedAt DATETIME,
    deletedAt DATETIME
);
DROP TABLE IF EXISTS USERS;
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idHouse INT,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(50),
    isVerified BOOLEAN DEFAULT FALSE,
    isBanned BOOLEAN DEFAULT FALSE,
    avatar TEXT,
    createdAt DATETIME,
    modifiedAt DATETIME,
    deletedAt DATETIME,
    FOREIGN KEY (idHouse) REFERENCES HOUSE(id)
);
DROP TABLE IF EXISTS USERS_LOG;
CREATE TABLE IF NOT EXISTS USERS_LOG (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idUser INT,
    date DATETIME,
    token VARCHAR(255),
    expiration DATETIME,
    state ENUM('email', 'ok'),
    FOREIGN KEY (idUser) REFERENCES USERS(id)
);
DROP TABLE IF EXISTS PET_CATEGORIES;
CREATE TABLE IF NOT EXISTS PET_CATEGORIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);
DROP TABLE IF EXISTS PET_COLORS;
CREATE TABLE IF NOT EXISTS PET_COLORS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);
DROP TABLE IF EXISTS PETS;
CREATE TABLE IF NOT EXISTS PETS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idHouse INT,
    name VARCHAR(255),
    avatar TEXT,
    idCategory INT,
    idColor INT,
    FOREIGN KEY (idHouse) REFERENCES HOUSE(id),
    FOREIGN KEY (idCategory) REFERENCES PET_CATEGORIES(id),
    FOREIGN KEY (idColor) REFERENCES PET_COLORS(id)
);
DROP TABLE IF EXISTS TYPES;
CREATE TABLE IF NOT EXISTS TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    idParent INT,
    FOREIGN KEY (idParent) REFERENCES TYPES(id)
);
DROP TABLE IF EXISTS PET_TYPES;
CREATE TABLE IF NOT EXISTS PET_TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    idType INT,
    FOREIGN KEY (idPet) REFERENCES PETS(id),
    FOREIGN KEY (idType) REFERENCES TYPES(id)
);
DROP TABLE IF EXISTS PET_PALS;
CREATE TABLE IF NOT EXISTS PET_PALS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    idPal INT,
    becamePalsAt DATETIME,
    FOREIGN KEY (idPet) REFERENCES PETS(id),
    FOREIGN KEY (idPal) REFERENCES PETS(id)
);
DROP TABLE IF EXISTS PATSNAPS;
CREATE TABLE IF NOT EXISTS PATSNAPS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPet INT,
    date DATETIME,
    caption TEXT,
    image TEXT,
    FOREIGN KEY (idPet) REFERENCES PETS(id)
);
DROP TABLE IF EXISTS PATS;
CREATE TABLE IF NOT EXISTS PATS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idPost INT,
    date DATETIME,
    FOREIGN KEY (idPost) REFERENCES PATSNAPS(id)
);